fix(appsemble): helm wait script

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -612,18 +612,21 @@ production:
     # Prevent a finished job without chart actually serving.
     - |
       retries=0
-      while [ $retries -lt 100 ]; do
+      found=0
+      while [ $retries -lt 100 ] && [ $found -ne 1 ]; do
         if helm search repo appsemble/appsemble --version "$CI_COMMIT_TAG"; then
           echo "Chart found!"
-          exit 0
+          found=1
         else
           echo "Chart not found, retrying in 5 seconds..."
           sleep 5
           retries=$((retries + 1))
         fi
       done
-      echo "Maximum number of attempts reached. Chart not found."
-      exit 1
+      if [ $found -ne 1 ]; then
+        echo "Maximum number of attempts reached. Chart not found."
+        exit 1
+      fi
     - helm upgrade appsemble appsemble/appsemble
       --debug
       --timeout 30m
